name: Testing custom JS action with self-hosted runner

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'

jobs:
  example_matrix:
    name: A job to say hello with a custom action and matrix
    runs-on: 'kkp-win-64'
    steps:  
      - name: Test self-hosted runner
        run: echo "Hello world"