name: Testing custom JS action with self-hosted runner

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'

jobs:
  example_matrix:
    name: A job to say hello with a custom action and matrix
    runs-on: ['self-hosted', 'windows', 'x64']
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:  
      - name: Test self-hosted runner
        run: echo "Hello world"