name: Testing custom JS action with matrix strategy

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'

jobs:
  example_matrix:
    strategy:
      # The number of jobs to run in parallel based on the attribute matrix
      # Let's say you have 2 jobs with 2 os and 2 node versions
      # This will create 2 * 2 = 4 jobs
      matrix:
        os: 
          - self-hosted
        node-version: [20]
    name: A job to say hello with a custom action and matrix
    runs-on: ${{ matrix.os }}
    steps:  
      #check owner
      - name: Check owner
        run: |
          echo "Checking owner"
          id
      
