name: Testing custom JS action with matrix strategy

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'

jobs:
  example_matrix:
    strategy:
      # The number of jobs to run in parallel based on the attribute matrix
      # Let's say you have 2 jobs with 2 os and 2 node versions
      # This will create 2 * 2 = 4 jobs
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - self-hosted, mac, arm64
        node-version: [20]
    name: A job to say hello with a custom action and matrix
    runs-on: ${{ matrix.os }}
    steps:  
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      # Add a step to build the js-action
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
    # Add a step to run the action
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: custom-js-action
        with:
          who-to-greet: '${{ github.event.inputs.name }} from ${{ matrix.os }}'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.custom-js-action.outputs.time }}"
